### PR TITLE
Use correct MSRV

### LINKED ISSUE #319: procfs 0.17.0 requires Rust 1.70.0
According to `Cargo.toml` `procfs` supports Rust `1.48`. However it fails to build on versions below 1.70.0.

We are currently using `procfs` with Rust 1.67.1, where we get the following error when compiling:
```
    Checking procfs-core v0.17.0
error[E0658]: use of unstable library feature 'is_some_and'
   --> /home/tyilo/.cargo/registry/src/github.com-1ecc6299db9ec823/procfs-core-0.17.0/src/crypto.rs:369:35
    |
369 |         .map(|line| line.as_ref().is_ok_and(|line| line.contains("fips")))
    |                                   ^^^^^^^^^
    |
    = note: see issue #93050 <https://github.com/rust-lang/rust/issues/93050> for more information

error[E0658]: use of unstable library feature 'is_some_and'
   --> /home/tyilo/.cargo/registry/src/github.com-1ecc6299db9ec823/procfs-core-0.17.0/src/crypto.rs:400:35
    |
400 |         .map(|line| line.as_ref().is_ok_and(|line| line.contains("geniv")))
    |                                   ^^^^^^^^^
    |
    = note: see issue #93050 <https://github.com/rust-lang/rust/issues/93050> for more information
```

Either the MSRV should be bumped or `procfs-core` should support Rust 1.48.

### PR DESCRIPTION
**Pull request by tyilo**
Fixes #319

### CODE REVIEW

**Comment by eminence** [comment]
Thank you!
